---
title: "NFL Play by Play"
author: "James Mahler"
date: "April 30, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library("shiny")
library("tidyverse")
library("readr")
library("plotly")
nfl_data <- read_csv("~/36-315/Project2/2017_pbp.csv")
# create categorical variables based on WPA and EPA to determine if a play was a "success"
nfl_data$isSuccess_EPA = ifelse(nfl_data$EPA>0 & !is.na(nfl_data$EPA), 1, 0)
nfl_data$isSuccess_WPA = ifelse(nfl_data$WPA>0 & !is.na(nfl_data$WPA), 1, 0)
# create categorical variable for yards to go
nfl_data$ytg = ifelse(nfl_data$ydstogo<4, "short",
                     ifelse(nfl_data$ydstogo<8, "medium",
                            ifelse(nfl_data$ydstogo<11, "long", "xlong")))
# create a categorical variable that merges Pass Location and Run Location to create
# a general direction variable
nfl_data$direction = NA  # new merged column start with NA
nfl_data$direction[!is.na(nfl_data$PassLocation)] = nfl_data$PassLocation[!is.na(nfl_data$PassLocation)]  # merge with pass location
nfl_data$direction[!is.na(nfl_data$RunLocation)] = nfl_data$RunLocation[!is.na(nfl_data$RunLocation)]  # merge with pass location


play_selection <- nfl_data %>%
  filter(!is.na(down), PlayType %in% c("Pass", "Run"),
         !is.na(direction), !is.na(EPA)) %>%
  group_by(down, ytg, PlayType) %>%
  summarise(count = n(),
            success_rate_wpa = sum(isSuccess_WPA)/count,
            avg_yds = sum(Yards.Gained)/count,
            epa_avg = sum(EPA) / count) %>%
  mutate(freq = count/sum(count))

play_selection_by_team <- nfl_data %>%
  filter(!is.na(down), PlayType %in% c("Pass", "Run"),
         !is.na(direction), !is.na(EPA)) %>%
  group_by(down, ytg, PlayType, posteam) %>%
  summarise(count = n(),
            success_rate_wpa = sum(isSuccess_WPA)/count,
            avg_yds = sum(Yards.Gained)/count,
            epa_avg = sum(EPA) / count) %>%
  mutate(freq = count/sum(count))

receiver_data <- nfl_data %>% 
  filter(PassOutcome == "Complete", down %in% c(1, 2, 3, 4)) %>% 
  group_by(Receiver, down, posteam) %>% 
  summarise(count = n(),
            air_yds = mean(AirYards),
            YAC = mean(YardsAfterCatch)) %>% 
  filter(count>5)

receiver_data_2 <- nfl_data %>% 
  filter(PlayType == "Pass", !is.na(Receiver)) %>% 
  group_by(Receiver) %>% 
  summarise(count = n(),
            catch_percent = sum(PassOutcome == "Complete")/count,
            avg_yds_when_targeted = mean(AirYards),
            avg_yds_gained_target = mean(Yards.Gained)) %>% 
  filter(count>25)

shinyApp(
  
  ui = fluidPage(
    inputPanel(
      selectInput("down", label = "Down:",
                  choices = c(1, 2, 3, 4), selected = 1),
      selectInput("distance", label = "Distance:",
                  choices = c("short", "medium", "long", "xlong"), selected = "long"),
      selectInput("team", label = "Team:",
                   choices = c("All", sort(unique(nfl_data$posteam))), selected = "All")
    ),
    
    plotOutput("play_plot"),
    plotlyOutput("EPA_plot"),
    plotlyOutput("receiver_plot"),
    plotlyOutput("receiver_plot_2")
  ),
  
  server = function(input, output) {
    output$play_plot <- renderPlot({
      if(input$team == "All"){
        ggplot(play_selection[play_selection$down == input$down & play_selection$ytg == input$distance,],
               aes(x = factor(PlayType), y = count, fill = success_rate_wpa)) + geom_bar(stat = "identity") +
          scale_fill_gradient(low = "gray100", high = "blue", limits = c(.15, .75)) +
          labs(title = "Play Selection by Down and Distance", x = "Play Type", y = "Count",
               fill = "Success Rate (WPA>0)")}
      else{
        ggplot(filter(play_selection_by_team, down == input$down, ytg == input$distance, posteam == input$team),
               aes(x = factor(PlayType), y = count, fill = success_rate_wpa)) + geom_bar(stat = "identity") +
          scale_fill_gradient(low = "gray100", high = "blue", limits = c(0, 1)) +
          labs(title = "Play Selection by Down, Distance and Team", x = "Play Type", y = "Count",
               fill = "Success Rate (WPA>0)")
      }
    })
    output$EPA_plot <- renderPlotly({
        EPA_plot <- ggplot(filter(play_selection_by_team, down == input$down, ytg == input$distance),
               aes(x = avg_yds, y = epa_avg, color = PlayType, label = posteam)) + geom_point() +
          labs(title = "Yards vs EPA for Each Team by Down and Distance", x = "Average Yards Gained",
               y = "EPA (Expeceted Points Added)", color = "Play Type")
        ggplotly(EPA_plot)
    })
    output$receiver_plot <- renderPlotly({
      if(input$team == "All"){
        yac_plot <- ggplot(filter(receiver_data, down == input$down, count>10),
                                aes(x = air_yds, y = YAC)) +
          geom_point(aes(text=sprintf("Receiver: %s<br>Catches: %s", Receiver, count))) +
          coord_cartesian(xlim = c(-5, 20), ylim = c(0, 15)) + geom_smooth(method = "loess") +
          labs(title = "Air Yards vs Yards After Catch by Down", x = "How Far Ball traveled in the Air",
               y = "Yards Gained After Catch")
      }
      else{
        yac_plot <- ggplot(filter(receiver_data, down == input$down, posteam == input$team),
                           aes(x = air_yds, y = YAC)) +
          geom_text(aes(label = Receiver, text=sprintf("Catches: %s", count))) +
          coord_cartesian(xlim = c(-5, 20), ylim = c(0, 15)) +
          labs(title = "Air Yards vs Yards After Catch by Down and Team", x = "How Far Ball traveled in the Air",
               y = "Yards Gained After Catch")
      }
      ggplotly(yac_plot)
    })
    output$receiver_plot_2 <- renderPlotly({
      yds_plot <- ggplot(receiver_data_2, aes(x = avg_yds_when_targeted,y = avg_yds_gained_target,
                                              color = catch_percent)) +
        geom_point(aes(text=sprintf("Receiver: %s<br>Targets: %s", Receiver, count))) +
        labs(title = "Air Yards vs Yards Gained for Receivers", x = "Average Air Yards When Targeted",
                            y = "Average Yards Gained per Target", color = "Catch Percentage")
      ggplotly(yds_plot)
    })
  },
  
  options = list(height = 550)
)

```

